// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRJ74-BCrfW1D1Bn68iiE-1QNS2IGSLY',
    appId: '1:280023587213:web:f5c55f7a3b148a9ccd45c4',
    messagingSenderId: '280023587213',
    projectId: 'meet-20ae7',
    authDomain: 'meet-20ae7.firebaseapp.com',
    storageBucket: 'meet-20ae7.appspot.com',
    measurementId: 'G-Q2WLYSQCHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-6XSFljODloKmfpaLUAxM_aLst6LO0c',
    appId: '1:280023587213:android:59db25be5b48ddf7cd45c4',
    messagingSenderId: '280023587213',
    projectId: 'meet-20ae7',
    storageBucket: 'meet-20ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBclINZCpdwDphlz67ybwBQhLe7fh2xpf4',
    appId: '1:280023587213:ios:5f7e417e542923f2cd45c4',
    messagingSenderId: '280023587213',
    projectId: 'meet-20ae7',
    storageBucket: 'meet-20ae7.appspot.com',
    iosBundleId: 'com.example.yaMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBclINZCpdwDphlz67ybwBQhLe7fh2xpf4',
    appId: '1:280023587213:ios:9e97fffd37d50711cd45c4',
    messagingSenderId: '280023587213',
    projectId: 'meet-20ae7',
    storageBucket: 'meet-20ae7.appspot.com',
    iosBundleId: 'com.example.yaMeet.RunnerTests',
  );
}
